export const cards = [
	{
		suit: 'diamond',
		value: 'ace',
		srcBack: '../img/backSide/backSide.png',
		srcFront: '../img/frontSide/diamond/ace.jpg',
		id: 1,
	},
	{
		suit: 'diamond',
		value: 'king',
		srcBack: '../img/backSide/backSide.png',
		srcFront: '../img/frontSide/diamond/king.jpg',
		id: 2,
	},
	{
		suit: 'diamond',
		value: 'queen',
		srcBack: '../img/backSide/backSide.png',
		srcFront: '../img/frontSide/diamond/queen.jpg',
		id: 3,
	},
	{
		suit: 'diamond',
		value: 'jack',
		srcBack: '../img/backSide/backSide.png',
		srcFront: '../img/frontSide/diamond/jack.jpg',
		id: 4,
	},
	{
		suit: 'diamond',
		value: 'ten',
		srcBack: '../img/backSide/backSide.png',
		srcFront: '../img/frontSide/diamond/ten.jpg',
		id: 5,
	},
	{
		suit: 'diamond',
		value: 'nine',
		srcBack: '../img/backSide/backSide.png',
		srcFront: '../img/frontSide/diamond/nine.jpg',
		id: 6,
	},
	{
		suit: 'diamond',
		value: 'eight',
		srcBack: '../img/backSide/backSide.png',
		srcFront: '../img/frontSide/diamond/eight.jpg',
		id: 7,
	},
	{
		suit: 'diamond',
		value: 'seven',
		srcBack: '../img/backSide/backSide.png',
		srcFront: '../img/frontSide/diamond/seven.jpg',
		id: 8,
	},
	{
		suit: 'diamond',
		value: 'six',
		srcBack: '../img/backSide/backSide.png',
		srcFront: '../img/frontSide/diamond/six.jpg',
		id: 9,
	},
	{
		suit: 'club',
		value: 'ace',
		srcBack: '../img/backSide/backSide.png',
		srcFront: '../img/frontSide/club/ace.jpg',
		id: 10,
	},
	{
		suit: 'club',
		value: 'king',
		srcBack: '../img/backSide/backSide.png',
		srcFront: '../img/frontSide/club/king.jpg',
		id: 11,
	},
	{
		suit: 'club',
		value: 'queen',
		srcBack: '../img/backSide/backSide.png',
		srcFront: '../img/frontSide/club/queen.jpg',
		id: 12,
	},
	{
		suit: 'club',
		value: 'jack',
		srcBack: '../img/backSide/backSide.png',
		srcFront: '../img/frontSide/club/jack.jpg',
		id: 13,
	},
	{
		suit: 'club',
		value: 'ten',
		srcBack: '../img/backSide/backSide.png',
		srcFront: '../img/frontSide/club/ten.jpg',
		id: 14,
	},
	{
		suit: 'club',
		value: 'nine',
		srcBack: '../img/backSide/backSide.png',
		srcFront: '../img/frontSide/club/nine.jpg',
		id: 15,
	},
	{
		suit: 'club',
		value: 'eight',
		srcBack: '../img/backSide/backSide.png',
		srcFront: '../img/frontSide/club/eight.jpg',
		id: 16,
	},
	{
		suit: 'club',
		value: 'seven',
		srcBack: '../img/backSide/backSide.png',
		srcFront: '../img/frontSide/club/seven.jpg',
		id: 17,
	},
	{
		suit: 'club',
		value: 'six',
		srcBack: '../img/backSide/backSide.png',
		srcFront: '../img/frontSide/club/six.jpg',
		id: 18,
	},
	{
		suit: 'heart',
		value: 'ace',
		srcBack: '../img/backSide/backSide.png',
		srcFront: '../img/frontSide/heart/ace.jpg',
		id: 19,
	},
	{
		suit: 'heart',
		value: 'king',
		srcBack: '../img/backSide/backSide.png',
		srcFront: '../img/frontSide/heart/king.jpg',
		id: 20,
		
	},
	{
		suit: 'heart',
		value: 'queen',
		srcBack: '../img/backSide/backSide.png',
		srcFront: '../img/frontSide/heart/queen.jpg',
		id: 21,
	},
	{
		suit: 'heart',
		value: 'jack',
		srcBack: '../img/backSide/backSide.png',
		srcFront: '../img/frontSide/heart/jack.jpg',
		id: 22,
	},
	{
		suit: 'heart',
		value: 'ten',
		srcBack: '../img/backSide/backSide.png',
		srcFront: '../img/frontSide/heart/ten.jpg',
		id: 23,
	},
	{
		suit: 'heart',
		value: 'nine',
		srcBack: '../img/backSide/backSide.png',
		srcFront: '../img/frontSide/heart/nine.jpg',
		id: 24,
	},
	{
		suit: 'heart',
		value: 'eight',
		srcBack: '../img/backSide/backSide.png',
		srcFront: '../img/frontSide/heart/eight.jpg',
		id: 25,
	},
	{
		suit: 'heart',
		value: 'seven',
		srcBack: '../img/backSide/backSide.png',
		srcFront: '../img/frontSide/heart/seven.jpg',
		id: 26,
	},
	{
		suit: 'heart',
		value: 'six',
		srcBack: '../img/backSide/backSide.png',
		srcFront: '../img/frontSide/heart/six.jpg',
		id: 27,
	},
	{
		suit: 'spade',
		value: 'ace',
		srcBack: '../img/backSide/backSide.png',
		srcFront: '../img/frontSide/spade/ace.jpg',
		id: 28,
	},
	{
		suit: 'spade',
		value: 'king',
		srcBack: '../img/backSide/backSide.png',
		srcFront: '../img/frontSide/spade/king.jpg',
		id: 29,
	},
	{
		suit: 'spade',
		value: 'queen',
		srcBack: '../img/backSide/backSide.png',
		srcFront: '../img/frontSide/spade/queen.jpg',
		id: 30,
	},
	{
		suit: 'spade',
		value: 'jack',
		srcBack: '../img/backSide/backSide.png',
		srcFront: '../img/frontSide/spade/jack.jpg',
		id: 31,
	},
	{
		suit: 'spade',
		value: 'ten',
		srcBack: '../img/backSide/backSide.png',
		srcFront: '../img/frontSide/spade/ten.jpg',
		id: 32,
	},
	{
		suit: 'spade',
		value: 'nine',
		srcBack: '../img/backSide/backSide.png',
		srcFront: '../img/frontSide/spade/nine.jpg',
		id: 33,
	},
	{
		suit: 'spade',
		value: 'eight',
		srcBack: '../img/backSide/backSide.png',
		srcFront: '../img/frontSide/spade/eight.jpg',
		id: 34,
	},
	{
		suit: 'spade',
		value: 'seven',
		srcBack: '../img/backSide/backSide.png',
		srcFront: '../img/frontSide/spade/seven.jpg',
		id: 35,
	},
	{
		suit: 'spade',
		value: 'six',
		srcBack: '../img/backSide/backSide.png',
		srcFront: '../img/frontSide/spade/six.jpg',
		id: 36,
	},
];