export const cards = [
	{
		suit: 'diamond',
		value: 'ace',
		srcBack: '../img/backSide/backSide.png',
		srcFront: '../img/frontSide/diamond/ace.jpg',
	},
	{
		suit: 'diamond',
		value: 'king',
		srcBack: '../img/backSide/backSide.png',
		srcFront: '../img/frontSide/diamond/king.jpg',
	},
	{
		suit: 'diamond',
		value: 'queen',
		srcBack: '../img/backSide/backSide.png',
		srcFront: '../img/frontSide/diamond/queen.jpg',
	},
	{
		suit: 'diamond',
		value: 'jack',
		srcBack: '../img/backSide/backSide.png',
		srcFront: '../img/frontSide/diamond/jack.jpg',
	},
	{
		suit: 'diamond',
		value: 'ten',
		srcBack: '../img/backSide/backSide.png',
		srcFront: '../img/frontSide/diamond/ten.jpg',
	},
	{
		suit: 'diamond',
		value: 'nine',
		srcBack: '../img/backSide/backSide.png',
		srcFront: '../img/frontSide/diamond/nine.jpg',
	},
	{
		suit: 'diamond',
		value: 'eight',
		srcBack: '../img/backSide/backSide.png',
		srcFront: '../img/frontSide/diamond/eight.jpg',
	},
	{
		suit: 'diamond',
		value: 'seven',
		srcBack: '../img/backSide/backSide.png',
		srcFront: '../img/frontSide/diamond/seven.jpg',
	},
	{
		suit: 'diamond',
		value: 'six',
		srcBack: '../img/backSide/backSide.png',
		srcFront: '../img/frontSide/diamond/six.jpg',
	},
	{
		suit: 'club',
		value: 'ace',
		srcBack: '../img/backSide/backSide.png',
		srcFront: '../img/frontSide/club/ace.jpg',
	},
	{
		suit: 'club',
		value: 'king',
		srcBack: '../img/backSide/backSide.png',
		srcFront: '../img/frontSide/club/king.jpg',
	},
	{
		suit: 'club',
		value: 'queen',
		srcBack: '../img/backSide/backSide.png',
		srcFront: '../img/frontSide/club/queen.jpg',
	},
	{
		suit: 'club',
		value: 'jack',
		srcBack: '../img/backSide/backSide.png',
		srcFront: '../img/frontSide/club/jack.jpg',
	},
	{
		suit: 'club',
		value: 'ten',
		srcBack: '../img/backSide/backSide.png',
		srcFront: '../img/frontSide/club/ten.jpg',
	},
	{
		suit: 'club',
		value: 'nine',
		srcBack: '../img/backSide/backSide.png',
		srcFront: '../img/frontSide/club/nine.jpg',
	},
	{
		suit: 'club',
		value: 'eight',
		srcBack: '../img/backSide/backSide.png',
		srcFront: '../img/frontSide/club/eight.jpg',
	},
	{
		suit: 'club',
		value: 'seven',
		srcBack: '../img/backSide/backSide.png',
		srcFront: '../img/frontSide/club/seven.jpg',
	},
	{
		suit: 'club',
		value: 'six',
		srcBack: '../img/backSide/backSide.png',
		srcFront: '../img/frontSide/club/six.jpg',
	},
	{
		suit: 'heart',
		value: 'ace',
		srcBack: '../img/backSide/backSide.png',
		srcFront: '../img/frontSide/heart/ace.jpg',
	},
	{
		suit: 'heart',
		value: 'king',
		srcBack: '../img/backSide/backSide.png',
		srcFront: '../img/frontSide/heart/king.jpg',
		
	},
	{
		suit: 'heart',
		value: 'queen',
		srcBack: '../img/backSide/backSide.png',
		srcFront: '../img/frontSide/heart/queen.jpg',
	},
	{
		suit: 'heart',
		value: 'jack',
		srcBack: '../img/backSide/backSide.png',
		srcFront: '../img/frontSide/heart/jack.jpg',
	},
	{
		suit: 'heart',
		value: 'ten',
		srcBack: '../img/backSide/backSide.png',
		srcFront: '../img/frontSide/heart/ten.jpg',
	},
	{
		suit: 'heart',
		value: 'nine',
		srcBack: '../img/backSide/backSide.png',
		srcFront: '../img/frontSide/heart/nine.jpg',
	},
	{
		suit: 'heart',
		value: 'eight',
		srcBack: '../img/backSide/backSide.png',
		srcFront: '../img/frontSide/heart/eight.jpg',
	},
	{
		suit: 'heart',
		value: 'seven',
		srcBack: '../img/backSide/backSide.png',
		srcFront: '../img/frontSide/heart/seven.jpg',
	},
	{
		suit: 'heart',
		value: 'six',
		srcBack: '../img/backSide/backSide.png',
		srcFront: '../img/frontSide/heart/six.jpg',
	},
	{
		suit: 'spade',
		value: 'ace',
		srcBack: '../img/backSide/backSide.png',
		srcFront: '../img/frontSide/spade/ace.jpg',
	},
	{
		suit: 'spade',
		value: 'king',
		srcBack: '../img/backSide/backSide.png',
		srcFront: '../img/frontSide/spade/king.jpg',
	},
	{
		suit: 'spade',
		value: 'queen',
		srcBack: '../img/backSide/backSide.png',
		srcFront: '../img/frontSide/spade/queen.jpg',
	},
	{
		suit: 'spade',
		value: 'jack',
		srcBack: '../img/backSide/backSide.png',
		srcFront: '../img/frontSide/spade/jack.jpg',
	},
	{
		suit: 'spade',
		value: 'ten',
		srcBack: '../img/backSide/backSide.png',
		srcFront: '../img/frontSide/spade/ten.jpg',
	},
	{
		suit: 'spade',
		value: 'nine',
		srcBack: '../img/backSide/backSide.png',
		srcFront: '../img/frontSide/spade/nine.jpg',
	},
	{
		suit: 'spade',
		value: 'eight',
		srcBack: '../img/backSide/backSide.png',
		srcFront: '../img/frontSide/spade/eight.jpg',
	},
	{
		suit: 'spade',
		value: 'seven',
		srcBack: '../img/backSide/backSide.png',
		srcFront: '../img/frontSide/spade/seven.jpg',
	},
	{
		suit: 'spade',
		value: 'six',
		srcBack: '../img/backSide/backSide.png',
		srcFront: '../img/frontSide/spade/six.jpg',
	},
];